### PR TITLE
GParsPoolUtil class implemented using Java Stream API

### LINKED ISSUE #49: Fix implementation of GParsPoolUtil class
Fix `GParsPoolUtil` class to satisfy all failing tests. Use Java Stream API for all parallel operations in combination with ForkJoinPool so thread pool size can be controlled with `withPool(x)` method.

przechwycenie obrazu ekranu_2017-07-08_14-38-16

@russel, please assign this task to me, I've already started working on it.

This task is related to #48

### PR DESCRIPTION
**Pull request by wololock**
Fixes #49 

This pull request fixes 130 failing test cases (125 left to fix). I've added a few more corner cases to `GParsPoolUtilTest` class, existing test assumptions were not removed.

@russel @vaclav please review and let me know if you find something worth improving or changing.

### CODE REVIEW

**Comment by wololock** [comment]
@russel Recent update adds support for running parallel computations on maps using `{ k, v -> ... }` and `{ k, v, index -> ... }` closures. I've discovered this use case while fixing implementation to satisfy `GParsPoolOnMapTest`. 22 more tests fixed now, 103 still left.

**Comment by russel** [comment]
@wololock I merged this pull request since it moves things on massively, and it is worth keeping master/HEAD as the most up-to-date version, even with things that will change again.

**Comment by wololock** [comment]
Yes, please suggest any changes to the current implementation. I'm not dogmatic on changes I've suggested :)

**Comment by russel** [comment]
I want to make sure I am not a blocker to progress so will merge pull requests that are not clearly wrong to merge. Just at the minute all progress is good progress. I will try to look things over and suggest or improvement further amendments, and indeed work on other bits myself. No promises for the next two or three weeks though (long story).

**Comment by wololock** [comment]
No worries, there is no rush. Don't feel forced by my recent activity - I will have less amount of time this week, but will try to make some small progress in bringing version 2.0.0 live.

**Pull request merged**
