### PR TITLE
Sample fix for eachParallel(Map, Closure)

### PR DESCRIPTION
**Pull request by noamt**
An initial suggestion for usage of JDK8 parallel Streams instead of Parallel Array

### CODE REVIEW

**Comment by russel** [comment]
I am hesitant to merge this one immediately: many of the changes are just indent changes, or changes to imports — in particular, star imports should be banned. However I like the contentful addition, but it seems unreasonable to make a changeset myself since that would lose the fact that @noamt made the original changeset.

**Comment by noamt** [comment]
Sorry, I hadn't realized so many formatting changes went in.
I'm not bothered with credits so feel free to pick the actual modification
and reject the pull request.
If it's easier, I could just create a cleaner request :)

**Comment by russel** [comment]
I have incorporated the changes from this pull request into a more extensive change that I shall commit shortly. Thanks for sending this pull request in.

**Comment by russel** [comment]
The Streams code in the eachParallel can throw checked exceptions, I think we need to have a plan as to how to deal with this. One possibility is to mutate the checked exceptions to unchecked ones.

**Comment by noamt** [comment]
Are checked exceptions really an issue? Groovy is the main (only?) consumer
of this

**Pull request closed without merging**
