### PR TITLE
Fix compilation errors for JDK8

### PR DESCRIPTION
**Pull request by benignbala**
Made a few fixes to get the compilation working.

### CODE REVIEW

**Comment by benignbala** [comment]
There is some test case that seems to hang for ever. Will debug that further. Thanks

**Comment by russel** [comment]
I like the parallelArray → parallelStream stuff, I think this is the way to go with this codebase. The swich from PAUtils to ParallelUtils is also good. The only reason for not merging this immediately is the removal of the files from the memoize directory in changeset 7314774. Is it certain these files are redundant?

**Comment by benignbala** [comment]
@russel The memoize related tests were removed because they were tests for class that were marked Deprecated and they classes were already completed commented out. Also, I guess since they are deprecated classes, we will eventually have to remove them. Thanks

**Comment by russel** [comment]
Ah, OK, that works for me.

**Comment by russel** [comment]
@benignbala Thanks for getting stuck in to helping sort out the jdk8 branch.

**Pull request merged**
