### PR TITLE
Remove duplicate *.adoc files already in GPars/Website/src/docs/archive

### PR DESCRIPTION
**Pull request by jnorthr**
These adoc's were part of the foundation of GPars/Website; we also hold a copy of them in GPars\Website\src\docs\archive\asciidoc as reference pending final removal

### CODE REVIEW

**Comment by russel** [comment]
@jnorthr  Sorry for not processing this pull request six months ago. Is it good to merge still. If so I'll just do it.

**Comment by jnorthr** [comment]
Yes Russel, i suspect it is but i will look@this again tomorrow before we do. It was oart of an idea to rationalize the content between GPars core and our website repo. More soon. Thanx.

**Comment by jnorthr** [comment]
Yes. Looks like everything is in the right place plus i have local copies of everything doc.s-wise, so we should be good to go. 👍

**Comment by jnorthr** [comment]
Yes. Looks like everything is in the right place plus i have local copies of everything doc.s-wise, so we should be good to go. Please merge. 👍

**Comment by jnorthr** [comment]
Looking at open issues. Issue 39 no longer applies as gpars.website no
longer exists. Can we close this one please ?

**Comment by jnorthr** [comment]
Issue 34 is to remove codehaus references which i have done for all website
documentation. There may still be some codehas within GPars core but have
not checked this.

**Comment by jnorthr** [comment]
Thank you.

**Pull request merged**
